"""create_saved_jobs_table

Revision ID: 1fbdc83c5b5f
Revises: 25cd603019f9
Create Date: 2025-12-14 10:52:59.164718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbdc83c5b5f'
down_revision: Union[str, Sequence[str], None] = '25cd603019f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_post_id', 'user_email', name='uix_saved_job_user')
    )
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_job_post_id'), 'saved_jobs', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_saved_at'), 'saved_jobs', ['saved_at'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_email'), 'saved_jobs', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_jobs_user_email'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_saved_at'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_post_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
