"""create_applications_table

Revision ID: 25cd603019f9
Revises: 3b9cb16a3013
Create Date: 2025-12-14 10:08:34.603934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cd603019f9'
down_revision: Union[str, Sequence[str], None] = '3b9cb16a3013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=255), nullable=False),
    sa.Column('applicant_email', sa.String(length=255), nullable=False),
    sa.Column('applicant_phone', sa.String(length=50), nullable=True),
    sa.Column('cv_document_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter_document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['cv_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_post_id', 'applicant_email', name='uix_job_applicant_email')
    )
    op.create_index(op.f('ix_applications_applicant_email'), 'applications', ['applicant_email'], unique=False)
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_post_id'), 'applications', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_post_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_email'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
