"""update_applications_tracking_fields

Revision ID: 39038e60c67d
Revises: c93a05f746d9
Create Date: 2025-12-18 20:43:28.167674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39038e60c67d'
down_revision: Union[str, Sequence[str], None] = 'c93a05f746d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('external_url', sa.String(length=500), nullable=True))
    op.add_column('applications', sa.Column('automation_status', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('application_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'application_data')
    op.drop_column('applications', 'automation_status')
    op.drop_column('applications', 'external_url')
    # ### end Alembic commands ###
