"""add_analytics_and_job_views

Revision ID: 59be893e7366
Revises: 1fbdc83c5b5f
Create Date: 2025-12-16 01:11:34.521029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59be893e7366'
down_revision: Union[str, Sequence[str], None] = '1fbdc83c5b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Job Views table
    op.create_table('job_views',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_post_id', sa.Integer(), nullable=False),
        sa.Column('viewer_email', sa.String(length=255), nullable=True),
        sa.Column('viewer_ip', sa.String(length=50), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('referrer', sa.String(length=500), nullable=True),
        sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_views_id'), 'job_views', ['id'], unique=False)
    op.create_index(op.f('ix_job_views_job_post_id'), 'job_views', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_job_views_viewed_at'), 'job_views', ['viewed_at'], unique=False)

    # Job Posts columns with defaults for existing data
    op.add_column('job_posts', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posts', sa.Column('applications_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posts', sa.Column('saves_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posts', sa.Column('status', sa.String(length=50), server_default='published', nullable=False))
    op.add_column('job_posts', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_posts', sa.Column('featured', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'featured')
    op.drop_column('job_posts', 'expires_at')
    op.drop_column('job_posts', 'status')
    op.drop_column('job_posts', 'saves_count')
    op.drop_column('job_posts', 'applications_count')
    op.drop_column('job_posts', 'views_count')
    # ### end Alembic commands ###
