"""add job_analyses table

Revision ID: be197a02c1ed
Revises: a4cd1173eb16
Create Date: 2025-12-07 13:48:46.245444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be197a02c1ed'
down_revision: Union[str, Sequence[str], None] = 'a4cd1173eb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False, comment='Must-have technical skills'),
    sa.Column('preferred_skills', sa.JSON(), nullable=False, comment='Nice-to-have skills'),
    sa.Column('experience_level', sa.String(length=50), nullable=False, comment='entry/junior/mid/senior/lead/principal'),
    sa.Column('min_years_experience', sa.Integer(), nullable=True, comment='Minimum years of experience'),
    sa.Column('max_years_experience', sa.Integer(), nullable=True, comment='Maximum years of experience'),
    sa.Column('education_requirements', sa.JSON(), nullable=False, comment='Education requirements'),
    sa.Column('certifications', sa.JSON(), nullable=False, comment='Certifications mentioned'),
    sa.Column('responsibilities', sa.JSON(), nullable=False, comment='Key responsibilities'),
    sa.Column('benefits', sa.JSON(), nullable=False, comment='Benefits and perks'),
    sa.Column('salary_range', sa.JSON(), nullable=True, comment='Salary range object with min, max, currency, period'),
    sa.Column('employment_type', sa.String(length=50), nullable=False, comment='full-time/part-time/contract/internship'),
    sa.Column('remote_policy', sa.String(length=50), nullable=True, comment='on-site/hybrid/fully-remote/flexible'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='Industry sector'),
    sa.Column('company_size', sa.String(length=50), nullable=True, comment='startup/small/medium/large/enterprise'),
    sa.Column('key_technologies', sa.JSON(), nullable=False, comment='Top technologies mentioned'),
    sa.Column('soft_skills', sa.JSON(), nullable=False, comment='Soft skills required'),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analyses_id'), 'job_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_job_analyses_job_post_id'), 'job_analyses', ['job_post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_analyses_job_post_id'), table_name='job_analyses')
    op.drop_index(op.f('ix_job_analyses_id'), table_name='job_analyses')
    op.drop_table('job_analyses')
    # ### end Alembic commands ###
